# Starter pipeline for deploying ARM templates

trigger:
- master  # This will trigger the pipeline on pushes to the master branch

pool:
  name: Azure Pipelines  # Specify the pool name where the agent will run

jobs:
  - job: armTemplateDeployment  # Name the job meaningfully
    steps:
      - task: AzureResourceManagerTemplateDeployment@3  # Task to deploy ARM templates
        inputs:
          deploymentScope: 'Resource Group'  # Scope of the deployment
          azureResourceManagerConnection: 'sn-test'  # Name of the service connection
          subscriptionId: '2f24afd5-0f94-4004-aa8a-cc88e903aceb'  # Azure subscription ID
          action: 'Create Or Update Resource Group'  # Action to create or update resources
          resourceGroupName: 'test'  # Name of the resource group
          location: 'East US'  # Location for the resource group
          templateLocation: 'Linked artifact'  # Update to indicate using linked artifact
          csmFileLink: 'https://raw.githubusercontent.com/mahesh6570/testarm/master/Win-VM_Template.json'  # Corrected raw URL
          csmParametersFileLink: 'https://raw.githubusercontent.com/mahesh6570/testarm/master/Win-VM_Parameters.json'  # Corrected raw URL
          deploymentMode: 'Incremental'  # Deployment mode (Incremental or Complete)
